// import libraries
import type { Metadata } from 'next'

// import components


// import fonts
import localFont from 'next/font/local'

const antarctica = localFont({
    src: '../fonts/Antarctica-Regular.woff2',
	display: 'swap',
	variable: '--font-antarctica'
})

// define metadata
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

// import css
import '@/styles/plugins/normalize.min.css'
import '@/styles/main.scss'
import TopMenu from '@/components/TopMenu'

// interface
interface RootLayoutProps {
    children: React.ReactNode
}

export default function RootLayout({ children } : RootLayoutProps) {
	return (
		<html lang='en'>
			
			<head>
				<link rel='shortcut icon' href='/img/favicon.svg' />
			</head>

			<body className={antarctica.className}>

				<TopMenu />
				
				{children}
				
			</body>

		</html>
	)
}