// import libraries
import type { Metadata } from 'next'

// import fonts
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

// define metadata
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

// import css
//import '@/styles/plugins/normalize.min.css'
//import '@/styles/plugins/bootstrap-grid.css'
import '@/styles/main.scss'

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				{children}
			</body>
		</html>
	)
}